version: '3'

services:
   wol:
     image: mkaczanowski/random-wol
     restart: always
     command: --host 0.0.0.0 --port 9090 --whitelist "127.0.0.1/32" --whitelist "192.168.1.0/24"
     network_mode: host
     ports:
       - "9090:9090"
